#!/usr/bin/env bash
source /Users/sbackus/.bash_profile

# set encoding
export LANG=en_US.UTF-8

# load rvm ruby
source /Users/sbackus/.rvm/environments/ruby-2.1.1@MTGFlavorCraver

bundle install
ruby /Users/sbackus/Code/MTGFlavorCraver/MTGFlavorCraver.rb